Write-Host 'UnsortedByteBenchmark'
dotnet run -p benchmarks/Lizt.Benchmarks/Lizt.Benchmarks.csproj --framework net5.0 -c Release 'UnsortedByteBenchmark'
Write-Host 'UnsortedShortBenchmark'
dotnet run -p benchmarks/Lizt.Benchmarks/Lizt.Benchmarks.csproj --framework net5.0 -c Release 'UnsortedShortBenchmark'
Write-Host 'UnsortedIntBenchmark'
dotnet run -p benchmarks/Lizt.Benchmarks/Lizt.Benchmarks.csproj --framework net5.0 -c Release 'UnsortedIntBenchmark'
Write-Host 'UnsortedDoubleBenchmark'
dotnet run -p benchmarks/Lizt.Benchmarks/Lizt.Benchmarks.csproj --framework net5.0 -c Release 'UnsortedDoubleBenchmark'
Write-Host 'SortedIntBenchmark'
dotnet run -p benchmarks/Lizt.Benchmarks/Lizt.Benchmarks.csproj --framework net5.0 -c Release 'SortedIntBenchmark'